### ISSUE TITLE
Pressing "Obtain lemmas" empties textbox

### ISSUE THREAD

**Issue by willismonroe** [oracc/nammu#333] opened 2018-07-24 19:21 UTC
This is on Nammu 1.0 running on Linux.

When I press the "Obtain lemmas" button the application clears out the entire textbox where the file contents are.

I've attached an error log from the console.

NB: This is an older project that might not reflect any recent changes to the oracc backend.  In any case, wiping a text field is probably undesirable behavior.

[Nammu error (incorectly configured project wipes text input).txt](https://github.com/oracc/nammu/files/2225032/Nammu.error.incorectly.configured.project.wipes.text.input.txt)

**Comment by raquel-ucl** [comment] 2018-07-25 05:54
Thanks for the report and for sending the log.

You are that is not the expected behaviour. We'll have a look into the problem and let you know.



From: M. Willis Monroe
Sent: Tuesday 24 July, 20:21
Subject: [oracc/nammu] Pressing "Obtain lemmas" empties textbox (#333)
To: oracc/nammu
Cc: Subscribed


This is on Nammu 1.0 running on Linux.
When I press the "Obtain lemmas" button the application clears out the entire textbox where the file contents are.
I've attached an error log from the console.
NB: This is an older project that might not reflect any recent changes to the oracc backend. In any case, wiping a text field is probably undesirable behavior.
Nammu error (incorectly configured project wipes text input).txt<https://github.com/oracc/nammu/files/2225032/Nammu.error.incorectly.configured.project.wipes.text.input.txt>

**Comment by sgrieve** [comment] 2018-07-26 10:02
Hi @willismonroe,

I have been investigating the error you have reported and have been able to reproduce it. Can I ask you to run the command `java -version` in your linux terminal and report the output here?

I suspect that the problem is that you are using Java 9 (which will show up as 1.9.xx). At present nammu 1.0.0 is only tested on Java 8.

Thanks

**Comment by willismonroe** [comment] 2018-07-30 18:15
java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by sgrieve** [comment] 2018-07-31 15:43
Hi @willismonroe,

We think we have fixed your problem, and will send you a new version of nammu to test in the next few days.

**Comment by sgrieve** [comment] 2018-08-02 09:44
Hi @willismonroe 

We have released version 1.0.1 of Nammu, which can be downloaded here: 
https://github.com/oracc/nammu/releases/download/1.0.1/nammu-1.0.1.jar

This version should have resolved the problems you initially reported. Please let us know if you have any further issues.

**Comment by sgrieve** [comment] 2018-08-17 10:41
@willismonroe Have you had any success with the new version?

**Comment by willismonroe** [comment] 2018-08-20 19:05
I have, it seems to work.  Thanks for the fix!

**Comment by raquel-ucl** [comment] 2018-08-21 16:55
Great! Thanks for letting us know. I'll close this issue then.

**Closed by raquel-ucl** 2018-08-21 16:55 UTC
