### ISSUE TITLE
Direction of script reversed in Nammu

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#297] opened 2017-10-13 23:23 UTC
I've somehow reversed the direction of script in Nammu so my text is showing right to left. No idea how this happened.

**Comment by EleanorRobson** [comment] 2017-10-14 12:08
Wow, good work! Now we know that Nammu *can* do right-left script :) Not yet an official feature though so I have NO idea how that happened or how to make it unhappen. Does quitting and restarting work? In any case, Raquel and the team will take a look on Monday.

**Comment by zarpanitu** [comment] 2017-10-14 14:29
Quitting and restarting didn't help. I also tried reinstalling Nammu on that computer, which also didn't help. I was fiddling with the settings as I'd had to start from scratch after a failed system software update, so I may have pressed "save" in one of the tabs that don't yet have any changeable settings. Aside from that, I only changed the font size and the working directory.

**Comment by sgrieve** [comment] 2017-10-16 08:21
Hi @zarpanitu, thanks for the bug report.

I am trying to reproduce this at the moment but am having no luck. Could you share the atf file you were working on and your settings file (which should be located in the `.nammu` folder in your home directory)? What is your operating system, and the operating system's native language/localisation settings - for example my machine is set to English(UK)

One other thing to try to fix the problem is to delete your `settings.yaml` file in the  `.nammu` directory (after you have sent us a copy!) and relaunch Nammu. This will regenerate a new settings file so if the error was created by you changing some settings this would resolve the issue.

Thanks!

**Comment by zarpanitu** [comment] 2017-10-16 13:05
I'm using Mac OS 10.13, language is English, region Canada. How do I submit files? (.atf and .yaml formats not supported by GitHub).

**Comment by sgrieve** [comment] 2017-10-16 13:44
Ah, sorry, I should have said. If you change the file extension to `.txt` then GitHub will allow them to be added here. Or you can email the files to me on `s.grieve[at]ucl.ac.uk`.

**Comment by sgrieve** [comment] 2017-10-17 08:24
Hi @zarpanitu It looks like there is a keyboard shortcut that none of us knew about that will change the text direction for Nammu.

If you make sure the focus is on the main editor window, e.g. that you can type text in it, and press `control` `shift` `O` (thats the letter O) the text should reverse.

Unfortunately we will need to do a bit more work to fully implement the right to left text before it can become an official feature.

Can you let me know if this does indeed fix your problem, and I will disable this shortcut in future releases and update the documentation in case anyone else has this problem.

**Comment by zarpanitu** [comment] 2017-10-17 13:32
Hi @sgrieve, thanks - I've tried control shift o and that doesn't work for me. I've also tried deleting Nammu and reinstalling from scratch, that also doesn't work. At least, the problem persists if I open one of my existing .atf files, but it doesn't occur if I start typing into a blank console. So maybe there's some issue with my files?

**Comment by sgrieve** [comment] 2017-10-19 15:00
Hi @zarpanitu, Thats a shame it doesn't work. I will keep investigating but in the meantime one solution might be to reinstall java on your machine, as it seems the problem is with java rather than Nammu itself.

There are uninstall instructions [here](https://www.java.com/en/download/help/mac_uninstall_java.xml) and install instructions [here](https://www.java.com/en/download/help/mac_install.xml)

**Comment by zarpanitu** [comment] 2017-10-19 15:16
Hi @sgrieve, I've uninstalled and reinstalled java, and now my script direction is back to normal! Thanks.

**Comment by sgrieve** [comment] 2017-10-20 07:26
Brilliant! I'm going to close this issue, but if the problem returns please let me know.

**Closed by sgrieve** 2017-10-20 07:26 UTC
